In [6]:
import numpy as np
from numpy.ma.core import arange

a = np.arange(2 * 2 * 4)#无其他特殊含义，就是乘法
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [5]:
import numpy as np
a=np.arange(2 * 2 * 4).reshape(2, 2, 4)
print(a.nbytes)#占用的内存大小
print(a.size*a.itemsize)#内存大小
print(a.itemsize)#每个元素占用的字节数
print(a.size)#返回原数的个数
print(a.shape)#形状
print(a.dtype)#数据类型

128
128
8
16
(2, 2, 4)
int64


In [4]:
import numpy as np
np.info(np.add)#info打印一个文档

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [7]:
import numpy as np
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [13]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
import numpy as np
x=[0,9,0,9,8,0]
indices=np.nonzero(x)[0]
print(indices)

[1 3 4]


In [1]:
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np
rng=np.random.default_rng(seed=42)
X=rng.random((3,3,3))
print(X)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


In [6]:
import numpy as np
rng=np.random.default_rng(seed=42)
X=rng.random((10,10))
print(X.min())
print(X.max())

0.007362269751005512
0.9756223516367559


In [11]:
import numpy as np
rng=np.random.default_rng(seed=42)
nums1=rng.uniform(low=10,high=20,size=(5,5))
nums2=rng.integers(low=0,high=10,size=(5,5))
print(nums1)
print(nums2)

[[17.73956049 14.3887844  18.5859792  16.97368029 10.94177348]
 [19.75622352 17.61139702 17.86064305 11.28113633 14.50385938]
 [13.70798024 19.26764989 16.4386512  18.22761613 14.43414199]
 [12.27238722 15.54584787 10.63817256 18.27631172 16.31664399]
 [17.5808774  13.54525968 19.70698024 18.93121121 17.78383497]]
[[7 1 3 4 4]
 [0 5 1 7 6]
 [9 7 3 9 4]
 [3 9 3 0 4]
 [7 1 4 1 6]]


In [24]:
import numpy as np
rng=np.random.default_rng(seed=42)
X=rng.integers(1,30,19)
X.mean()#求和
X.prod()#元素的积
X.std()#标准差
X.var()#方差
X.argmax()#最小值索引
X.argsort()#按位排序
np.median(X)#这个需要函数来算

np.float64(19.0)

In [28]:
import numpy as np
X=np.arange(9).reshape(3,3)
print(X)
np.percentile(X,50,axis=1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([1., 4., 7.])

In [32]:
import numpy as np
n=5
X=np.ones((n,n),dtype=int)
X[1:-1,1:-1]=0
print(X)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [20]:
#对于np.pad的应用
import numpy as np
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)#pad_width可以是()()的形式
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
import numpy as np
Z = np.ones((5, 5))
Z[:,[0,-1]]=0
Z[[0,-1],:]=0
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
import numpy as np
0*np.nan#表示缺失值的意思,inf(infinity)是无穷大的意思
np.nan==np.nan#
np.inf>np.nan#任何与np.nan比较的都是false,只有np.nan！=np.nan是ture检验一般用isnan()
np.nan - np.nan#nan
np.nan in set([np.nan])#ture,(集合set可行list不行,set是identity识别法,list是==，so,false
0.3 == 3 * 0.1#两者在二进制层面不相等。

False

In [36]:
import numpy as np
Z = np.diag(1+np.arange(4), k=0)
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [38]:
import numpy as np
z=np.zeros((10,10))
z[1::2,::2]=1;#1::2奇数索引
z[::2,1::2]=1;#::2偶数索引
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [39]:
import numpy as np
shape = (6, 7, 8)
index = np.unravel_index(99, shape)  # 第100个元素 = 索引99,unravel_index是对一维变多维的工具
print(index)  # (1, 5, 3)

(np.int64(1), np.int64(5), np.int64(3))


In [41]:
import numpy as np
print(np.unravel_index(99,(6,7,8)))#unravel_index是将一维的数字化为多维

(np.int64(1), np.int64(5), np.int64(3))


In [53]:
import numpy as np
z=np.array([[1,0],
            [0,1]])
z=np.tile(z,(2,3))
print(z)

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


In [56]:
#归一化的一种方法
import numpy as np
rng=np.random.default_rng(seed=42)
Z=rng.integers(low=0,high=10,size=(5,5))
Z_norm = (Z - Z.min()) / (Z.max() - Z.min())#[min, max] → [0, max-min]// X`=X-Xmin/Xmax-Xmin
#这样就把范围缩小到[0,1]之间
print("原始范围:", Z.min(), "to", Z.max())
print("归一化后:", Z_norm.min(), "to", Z_norm.max())  # 0.0 to 1.0

原始范围: 0 to 9
归一化后: 0.0 to 1.0


In [57]:
#Z-Score 标准化
import numpy as np
rng=np.random.default_rng(seed=42)
Z=rng.integers(low=0,high=10,size=(5,5))
Z_std=(Z-Z.mean())/Z.std()
print("均值",Z_std.mean())
print("标准化",Z_std.std())

均值 1.3322676295501878e-17
标准化 0.9999999999999999


In [119]:
rng=np.random.default_rng(seed=42)
Z = rng.random((5, 5))
# 每行归一化（使每行向量长度为1）
Z_l2 = Z / np.linalg.norm(Z, axis=1, keepdims=True)#确保广播运算正常进行
row_norms = np.linalg.norm(Z_l2, axis=1)
print(Z_l2)
print(row_norms)

[[0.54401465 0.30848819 0.60350953 0.49018084 0.06619737]
 [0.63395817 0.49458762 0.51078359 0.08324808 0.29266021]
 [0.24532503 0.61316036 0.42598995 0.54435031 0.29336888]
 [0.18889085 0.46099533 0.05304772 0.68796353 0.5250673 ]
 [0.4343514  0.20312801 0.55616787 0.51171967 0.44597999]]
[1. 1. 1. 1. 1.]


(255, 0, 0, 255)
R=255, G=0, B=0, A=255
[255   0   0 255]
